services:
  debian-dev:
    image: ghcr.io/100apps/dev-container:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: debian-trixie-ssh
    ports:
      - "8022:22"
    volumes:
      - /data:/data
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
